baseurl = "https://app.ytk.edu.ru/food-organizations"
languageCode = "en-us"
defaultContentLanguage = "ru"
metadataformat = "yaml"
defaultContentLanguageInSubdir= true
title = "Организация питания"
theme = "hugo-theme-learn"

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
	name = "greysoft"
	description = "Technical equipment of catering facilities - hugo project."

	github_user   = "greysoftcrazy"
	github_repo   = "https://github.com/greysoftcrazy/Technical-equipment-of-catering-facilities-hugo-project"
	github_banner = true

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicon = "favicon.ico"
    themeVariant = "mine"
	showVisitedLinks = true
    disableBreadcrumb = false
    disableNextPrev = false
	disableAssetsBusting = true
	disableInlineCopyToClipBoard = true
    ordersectionsby = "weight"
    disableShortcutsTitle = false

[params.sidebar]
	logo = "favicon.ico"


	github_button  = true
	travis_button  = false
	codecov_button = false
	gratipay = ""

	show_relations = true

[params.footer]
	copyright = "[greysoft](https://github.com/greysoftcrazy)"
	show_powered_by = true
